name: Deploy to Server 

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v1

      - name: Remove old files 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            rm -rf ${{ secrets.PATH }}/* 
            if [ -f "async_commands_pids.txt" ]; then
              echo "Terminating previous async commands..."
              while read pid; do
                echo "Killing process $pid"
                kill $pid || true
              done < async_commands_pids.txt
              rm async_commands_pids.txt
            else
              echo "No previous async commands found."
            fi
      
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          source: "."
          target: ${{ secrets.PATH }}
          
      - name: Install NVM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          
      - name: Setup Node.js environment 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 20.2.0
            nvm alias default 20.2.0
            node -v          
      - name: Print node version 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: whoami 

      - name: Build the lib 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: cd ${{ secrets.PATH }} && cd siws_lib && npm install && npm run build
 
      - name: Deploy backend 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.PATH }} 
            source ~/.bashrc
            cd backend
            nvm install 20.2.0
            nvm use 20.2.0
            npm install  
            command1="npm run start"
            $command1 &
            echo $! >> ~/async_commands_pids.txt 
      
      - name: Deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.PATH }} 
            cd frontend
            npm install  
            npm run build 
            command1="npm run start"
            $command1 &
            echo $! >> ~/async_commands_pids.txt 
