name: Deploy to Server 

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v1

#      - name: Remove old files 
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          port: ${{ secrets.PORT }}
#          key: ${{ secrets.SSHKEY }}
#          script: |
#            rm -rf ${{ secrets.PATH }}/* 
#            if [ -f "async_commands_pids.txt" ]; then
#              echo "Terminating previous async commands..."
#              while read pid; do
#                echo "Killing process $pid"
#                kill $pid || true
#              done < async_commands_pids.txt
#              rm async_commands_pids.txt
#            else
#              echo "No previous async commands found."
#            fi
#      
#      - name: Copy repository contents via scp
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          port: ${{ secrets.PORT }}
#          key: ${{ secrets.SSHKEY }}
#          source: "."
#          target: ${{ secrets.PATH }}

      - name: Install SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          
      - name: Check Node.js version
        env:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          PROJECT_PATH: ${{ secrets.PATH }}
        run: |
          ssh $REMOTE_USER@$REMOTE_HOST "source ~/.bashrc && node -v"          

      - name: Build the lib 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: cd ${{ secrets.PATH }} && cd siws_lib && npm install && npm run build
 
      - name: Deploy backend 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.PATH }} 
            source ~/.bashrc
            cd backend
            nvm install 20.2.0
            nvm use 20.2.0
            npm install  
            command1="npm run start"
            $command1 &
            echo $! >> ~/async_commands_pids.txt 
      
      - name: Deploy frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.PATH }} 
            cd frontend
            npm install  
            npm run build 
            command1="npm run start"
            $command1 &
            echo $! >> ~/async_commands_pids.txt 
